### PR TITLE
Feature/mobile layout

### PR DESCRIPTION
**Pull request by real-Lost**
Working off of @ImaginaryLost 's work, I added a mobile layout and addressed all the issues brought up in #2 except the 'types' thing

### CODE REVIEW

**Comment by bf-v** [comment]
For a pr titled `mobile layout`, the scope here is pretty large. would you mind splitting out individual features? in addition, it seems like @ImaginaryLost is planning to continue to work on their pr, so including those changes here would infringe upon their work.

**Comment by ImaginaryLost** [comment]
My original plan was to resubmit an PR tomorrow for multiple files with the changes to master and PR comments, my WIP branch currently has the mobile layout commits from @real-Lost included. If @real-Lost or @bf-v would prefer I leave out any mobile changes I can do that as well.

In reference to infringing on work, I assumed, which perhaps I shouldn't, that this would licensed under something like MIT so there would be no infringing and we would be free to collaborate on this project. I've created an issue for that here https://github.com/bf-v/bfv/issues/8

**Comment by real-Lost** [comment]
Yeah the scope of my pr is bit larger then it should be, I'll try to implement the mobile stuff after @ImaginaryLost 's code is pushed to the master.

Btw, I didn't mean to infringe on anyone's code, I assumed since the commit history has the commits from @ImaginaryLost it would be fine if I build on it.

**Comment by bf-v** [comment]
ah i see, thanks for clearing up the confusion for me. It looks like both of you are working on branches with each others' commits and have similar functionality, so i guess it would make sense if only one of you made the pr, or otherwise split out the functionality so that @real-Lost's pr contains mobile layout and @ImaginaryLost's contains the multiple files as per their original pr. If any of you have different ideas then feel free to bring them up, i am open to discussion.

**Pull request closed without merging**
